/**
 * OpenAI Assistant IDs (Dual Tier)
 *
 * Generated by: npx tsx scripts/setup-assistants.ts
 *
 * Two tiers of domain assistants:
 * - general: vector store with unrestricted Confluence pages only
 * - manager: vector store with ALL Confluence pages (general + restricted)
 *
 * Classifier and escalation are shared (no file search, role-agnostic).
 *
 * STOPGAP: Browser calls Assistants API directly.
 * PRODUCTION: Replace with backend using OpenAI Agents SDK.
 */

export type UserRole = 'general' | 'manager';

export const ASSISTANT_IDS = {
  classifier: 'asst_KqvOTkovieN165q3Ra8GWJlO',
  escalation: 'asst_Bl9VhFXAdHuDLpX3MzIAnPcm',
  general: {
    performance: 'asst_sYavgrSqakmyEGckijGjamGF',
    conversation: 'asst_3Si8pMROlcLyUXb6NMXDedUy',
    policy: 'asst_izc7w5azGUSECuXnjUkPxkJz',
    separation: 'asst_Hn7bZqqLIx92AzKfqQYEocfD',
    career: 'asst_Mp0OGqAeDDBBnfz9o1khX5iU',
    feedback: 'asst_XW71vhUrcWcDVEYVUtOvAU3o',
  },
  manager: {
    performance: 'asst_uizjgpZmRWzNa8puKBEdWiTj',
    conversation: 'asst_hTMnaDNZoZIFNmzRXC3O0Hef',
    policy: 'asst_G0n7dZw7C2vIaLdMThV13kxt',
    separation: 'asst_HPrL4sfQ2AydUAusRFUzQc7e',
    career: 'asst_EPxBrnPZW5eKygrboQAajJzl',
    feedback: 'asst_4Ljtzkd7VkF9Yge3h5G6oFOM',
  },
};

type DomainRoute = 'performance' | 'conversation' | 'policy' | 'separation' | 'career' | 'feedback';

export function getAssistantId(route: string, role: UserRole): string {
  if (route === 'escalation') return ASSISTANT_IDS.escalation;
  const tier = ASSISTANT_IDS[role];
  return tier[route as DomainRoute] ?? tier.policy;
}
