/**
 * OpenAI Assistant IDs
 *
 * Generated by: npx tsx scripts/setup-assistants.ts
 *
 * STOPGAP: These assistants are called directly from the browser via
 * the Assistants API. In production, replace this with a backend service
 * that uses the OpenAI Agents SDK to orchestrate the workflow server-side.
 *
 * Backend migration plan:
 * 1. Deploy a Node.js backend service (see provisioning discussion)
 * 2. Backend holds the OpenAI API key and Confluence token
 * 3. Backend uses the Agents SDK (same code as the OpenAI builder export)
 * 4. Frontend calls the backend's REST API instead of OpenAI directly
 * 5. Remove API key from localStorage / settings panel
 * 6. Auth handled by corporate SSO at the ingress level
 */

export const ASSISTANT_IDS = {
  classifier: 'asst_jEqFB2ovBwYyem1OgdBRtRAW',
  escalation: 'asst_5Bn4Y1vuUHpvj7ZT62XCnT6m',
  performance: 'asst_2nIW1O6mMYuGgTWpEymi0Rjx',
  conversation: 'asst_W1dO5e9e4dzgbWNZ7VnH20ms',
  policy: 'asst_kIEWkZwnh15NC7ikKM9opkVd',
  separation: 'asst_4E77rMdBHx3c4Bkmoq1smqMl',
};
