/**
 * OpenAI Assistant IDs (Dual Tier)
 *
 * Generated by: npx tsx scripts/setup-assistants.ts
 *
 * Two tiers of domain assistants:
 * - general: vector store with unrestricted Confluence pages only
 * - manager: vector store with ALL Confluence pages (general + restricted)
 *
 * Classifier and escalation are shared (no file search, role-agnostic).
 *
 * STOPGAP: Browser calls Assistants API directly.
 * PRODUCTION: Replace with backend using OpenAI Agents SDK.
 */

export type UserRole = 'general' | 'manager';

export const ASSISTANT_IDS = {
  classifier: 'asst_Z80QDpR7vBfPD3AybfMTtmMI',
  escalation: 'asst_ILlD4D0iWja22rEpFx1Z1cHV',
  general: {
    performance: 'asst_rv5KDbupjOttcqsJqDSZRorg',
    conversation: 'asst_Wznw66uGX2shOz5JhulLcqjV',
    policy: 'asst_EezRSJ435MMhpvJWKL8i8rCd',
    separation: 'asst_g74hv9Gq5aECXp2SCAVWsdx1',
  },
  manager: {
    performance: 'asst_DLZKrLJYfdESX27RtY5FkbbG',
    conversation: 'asst_Pa81conwymSnxuaMjVxTLJRW',
    policy: 'asst_gylPFYTBBaAARzbp3anuC2Zw',
    separation: 'asst_tKTquBvJ8afrtW1XXU2lajBV',
  },
};

type DomainRoute = 'performance' | 'conversation' | 'policy' | 'separation';

export function getAssistantId(route: string, role: UserRole): string {
  if (route === 'escalation') return ASSISTANT_IDS.escalation;
  const tier = ASSISTANT_IDS[role];
  return tier[route as DomainRoute] ?? tier.policy;
}
